title: Robin Goyal
description: "I enjoy tinkering with technology."
author:
  name: "robingoyal"
  email: "robin.goyal.swd@gmail.com"
  url: "https://blog.rgoyal.net"

url: "https://blog.rgoyal.net"
baseurl: /

source: .
destination: ./_site
permalink: /posts/:title
paginate: 4
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "robingoyal"
google_analytics: G-MPJ1WVX7TP