# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Robin Goyal
tagline:             'Developer, Engineer, Student'
description:         'Thoughts, discussions, and notes about the unending journey in software development'
url:                 http://lanyon.getpoole.com
baseurl:             ''

gems:               [jekyll-paginate]
paginate:            5
paginate_path:      "page:num"

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
